# Generated by Django 3.1.6 on 2021-05-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='c_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mails',
            name='message',
            field=models.TextField(max_length=2000),
        ),
    ]
